### ISSUE TITLE
Benchmarks for default Rails setup

### ISSUE THREAD

**Issue by nickhammond** [npezza93/solid_cable#1]
Hey @npezza93,

I mentioned your gem over on the Rails 8 issue for having a DB backed ActionCable, just a heads up. I started using it on a project today and so far it's been pretty great. Previously I was using litestack but noticed that some of the hotwire functionality(turbo refreshes) wasn't working properly. 

https://github.com/rails/rails/issues/50480#issuecomment-2138008715

**Comment by npezza93** [comment]
Oh sick! Thanks for that. Yea ill see if i can come up with a way to benchmark this

**Comment by nickhammond** [comment]
Sounds good, thanks or making the gem! So far so good with the app I integrated this with but I'll keep an eye on it and post if anything comes up.

**Comment by npezza93** [comment]
Sounds good! Appreciate it
