### ISSUE TITLE
Consider using a channel_hash column and index

### ISSUE THREAD

**Issue by djmb** [npezza93/solid_cable#13]
Solid Cable is using 500 bytes for the channel in the index. By generating a `channel_hash` column and indexing that instead we could have a much more compact index. WDYT @npezza93?

In Solid Cache we use an [8 byte integer](https://github.com/rails/solid_cache/blob/52bd211fea952291b423aad0709ed343df5e0b65/lib/generators/solid_cache/install/templates/db/cache_schema.rb#L8) generated from the [start of a Digest::SHA256.digest](https://github.com/rails/solid_cache/blob/52bd211fea952291b423aad0709ed343df5e0b65/app/models/solid_cache/entry.rb#L111).

**Comment by npezza93** [comment]
Sweet! Thanks for this @djmb. Opened up #14 to address this.
