### ISSUE TITLE
Production-ready?

### ISSUE THREAD

**Issue by darinwilson** [npezza93/solid_cable#2]
Apologies that this more of a question than an issue, but I found this repo thanks to @nickhammond's [comment in a Rails issue](https://github.com/rails/rails/issues/50480#issuecomment-2137804922) and would love to it a try.

But I was wondering you're currently using it in production, or if it's still in an experimental stage? Any rough edges that would be good to know about?

In any case, thanks so much for working on this - it's definitely needed!

**Comment by npezza93** [comment]
Yea this is ready to roll and im using it in production currently. Wrapping up some of the api and prepping to cut v1.

**Comment by nickhammond** [comment]
Party, congrats @npezza93!

**Comment by nickhammond** [comment]
@npezza93 If you run the same benchmarks with litestack does the litedb adapter perform any better than native sqlite3?

**Comment by nickhammond** [comment]
@npezza93 Also, since solid_cable is DB agnostic it'd be great to run these against mysql/postgres. I can help with this on Digital Ocean and a local mysql/postgres instance. I'll use what I can from your benchmark comments and run this tomorrow. I'll try and run this as a single file Rails app so we can re-use the same setup too https://greg.molnar.io/blog/a-single-file-rails-application/

**Comment by npezza93** [comment]
Cool. I wouldnt bother with postgres since it has it's own dedicated action cable adapter.

**Comment by npezza93** [comment]
As for litestack:

I ran sqlite3 with the patches described here: https://github.com/rails/rails/pull/50371#issuecomment-2145725946 and against rails main so it should be virtually identical. Didnt end up with any read locks or anything

**Comment by nickhammond** [comment]
@npezza93 Well the current pg adapter has size limitations for what can be sent over the wire, solid_cable would be a great replacement for those limitations.

**Comment by nickhammond** [comment]
@npezza93 _Heard_ on sqlite3/litestack. That's a great thread, thanks for sharing.

**Comment by npezza93** [comment]
Oh interesting. How big is the limitation?

**Comment by nickhammond** [comment]
[8k](https://stackoverflow.com/questions/39571553/configuration-for-action-cable-for-postgresql) so for simple over the wire and views it's fine but it's sort of unpredictable because you have to keep that in mind when building an app with hotwire.

**Comment by darinwilson** [comment]
> Yea this is ready to roll and im using it in production currently. Wrapping up some of the api and prepping to cut v1.

That's great news - thanks so much!
